[project]
name = "appscriptz"
version = "0.1.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "llama-index>=0.12.36", "llmada>=0.1.11", "promptlibz>=0.2.7", "pytest>=8.3.5",]

[tool.pytest.ini_options]
testpaths = [ "tests",]
pythonpath = [ "src",]
